### ISSUE TITLE
Click en programas - Cooperación Técnica - click en cualquier nombre, y te lleva a la página principal

### ISSUE THREAD

**Issue by mugul** [cadena-si-usb/SiraDex#14]

**Comment by J0hnG4lt** [comment]
Hola. No pude replicar este error (teniendo rol de admin) con la versión de siradex que está corriendo. 
¿Podrías indicar el hash del commit o la rama donde encontraste este problema?

**Comment by RumbosN** [comment]
Esto pasa cuando se tiene el rol de usuario, al seleccionar un tipo de actividad
