### ISSUE TITLE
El codigo del programa deberia admitir numeros

### ISSUE THREAD

**Issue by RumbosN** [cadena-si-usb/SiraDex#2]
tal como lo hace el de tipo de actividad

**Comment by J0hnG4lt** [comment]
Podrías clarificar este punto, @RumbosN?
_Tipo_de_actividad_, en efecto, tiene un **código.** Por su parte, _programa_ tiene una **abreviación.** 
Eso significa que si hay números allí, entonces debe haber números en el nombre.
¿Hay alguna razón por la cual no se permiten números en el nombre del programa y en su abreviación?
Si mal no recuerdo, era problemático permitirlos.
