### ISSUE TITLE
correccion de rutas, una ruta que no esta registrada no deberia lanzar error si no redirigir a una previa o una por defecto de not found

### ISSUE THREAD

**Issue by RumbosN** [cadena-si-usb/SiraDex#21]
Al quitar el numero de la ruta de agregar dio el sig error
![2017-03-09-092623_1366x768_scrot](https://cloud.githubusercontent.com/assets/12719355/23752187/aaade9f8-04aa-11e7-9d66-47ee55efd7d0.png)

**Comment by J0hnG4lt** [comment]
Creo haberlo arreglado en el commit mencionado arriba. Este problema ocurría en varias partes del sistema.
