### ISSUE TITLE
Para tipo de actividad

### ISSUE THREAD

**Issue by RumbosN** [cadena-si-usb/SiraDex#25]
Acepta descripciones con saltos de lineas pero al visualizar la actividad, se borran los saltos de linea y no se ve confusa la descripcion. Para evitar esto se puede hacer uso de las etiquetas P que se configuran con web2py o guardar con las etiquetas html las descripciones

Si se tiene el rol de usuario, y en las actividades de un programa se le hace click a una, te bota de la vista y se va a la principal. Deberia desabilitar el enlace o simplemente permanecer en la vista

Al darle click al ojo en las actividad, si la descripcion se muy larga, no se muetra toda, tampoco si tiene saltos de linea

**Comment by leotms** [comment]
El punto "Si se tiene el rol de usuario, y en las actividades de un programa se le hace click a una, te bota de la vista y se va a la principal. Deberia desabilitar el enlace o simplemente permanecer en la vista" ya fue solucionado, pues tenia su propio issue (#14).

**Comment by leotms** [comment]
Solucionado, revisado en commit #e3124af
