### ISSUE TITLE
CP7-ES5-FA9

### ISSUE THREAD

**Issue by CinthyaRamos** [cadena-si-usb/SiraDex#35]
Al ingresar en el campo adicional "cantidad decimal" los valores erroneos muestra el siguiente tickets, tener en cuenta que el campo adicional es obligatorio y se tenia el conjunto de campos adicionales obligatorios: fecha, texto corto, texto largo, cantidad entera, fecha, documento, fecha y cantidad decimal.

![image](https://cloud.githubusercontent.com/assets/17190115/23825407/b40814c2-065f-11e7-87af-5bb31edd7151.png)

**Comment by RumbosN** [comment]
No se pudo replicar el problema, por favor coloca el nombre del proograma y la actitvidad con la que probaste, ademas de los valores colocados para intentar replicarlo

**Comment by leotms** [comment]
Cerrando Issue. Hasta el commit #63f78df no se ha podido replicar. Bien se solucionó como efecto de otros cambios o ya no existe por la version de la BD. Si reaparece se reabrirá el issue.
