### ISSUE TITLE
Usuario Dex intentando validar error

### ISSUE THREAD

**Issue by RumbosN** [cadena-si-usb/SiraDex#51]
salio un campo adicional, ademas del nombre, para cambiar el id del programa y luego dio un error raro

**Comment by leotms** [comment]
No se ha podido replicar, incluso desde el servidor con una cuenta de DEx. Algun otro detalle que recuerdes de este error? @RumbosN

**Comment by leotms** [comment]
No se pudo replicar, cerrando.
