### ISSUE TITLE
Al usar los campos de un catálogo no se pueden agregar más atributos

### ISSUE THREAD

**Issue by J0hnG4lt** [cadena-si-usb/SiraDex#57]
Si se quiere añadir campos adicionales con un template de catálogos, luego se bloquea la opción de seguir agregando campos. Además, los campos del catálogo pueden tener nombre similares a campos adicionales simples, lo cual es problemático.

**Comment by leotms** [comment]
No pudo replicarse. Si reaparece el issue se reabre.
