### ISSUE TITLE
Botón cambia su texto erróneamente en carga de comprobantes

### ISSUE THREAD

**Issue by mugul** [cadena-si-usb/SiraDex#6]
Al crear un producto, adjuntar 5 comprobantes y hacer click en guardar como borrador.

Los botones de guardar como borrador y enviar cambian su texto a "Trabajando..." por unos segundos, y luego los dos dicen "Guardar como borrador"...

Considero que deberían decir "Trabajando" hasta que la página actualice y guarde el borrador.
(O mostrar el proceso de carga, pero creo q es pedir mucho xD)

**Comment by J0hnG4lt** [comment]
No pude replicar exactamente este issue. Lo único es que en mi caso los botones dicen "working"

**Comment by mugul** [comment]
Crea un producto, adjunta los 5 comprobantes al mismo tiempo, y dale a guardar como borrador... (Si tu internet es muy chola limítalo un poco... me sucede cuando intenta cargar algo y demora mucho tiempo (unos 5 o 6 segundos)

Los dos botones diran "Trabajando..." y luego los dos cambian a "Guardar como borrador"..

Es posible que la función que cambia el estado del botón sea la misma.

Si no logras recrearlo, intenta subir los 5 documentos al mismo tiempo que pesen cerca de 2mb
![3](https://cloud.githubusercontent.com/assets/9275662/23404716/c34294a2-fd8c-11e6-823f-2af71b9eef2d.png)

PD: Las pruebas las estoy haciendo con lo q está montado en el servidor

**Comment by RumbosN** [comment]
A mi tambien me paso con lo que esta montado en el servidor

**Comment by leotms** [comment]
No se pudo replicar con lo que esta en el servirdor, la carga de documentos tardo mas de 2 minutos y no hubo cambio en los botones. Si reaparece el issue se reabre.
